[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jhu-assembly-linter"
version = "0.1.0"

[project.scripts]
jhu-assembly-linter = "jhu_assembly_linter.cmd:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
